name: Automação Bing

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get update
          sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
          google-chrome --version

      - name: Instalar ChromeDriver compatível
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          CHROME_MAJOR=$(echo $CHROME_VERSION | cut -d. -f1)
          echo "Versão major do Chrome: $CHROME_MAJOR"
          
          DRIVER_VERSION=$(curl -s https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions.json | jq -r ".channels.Stable.version")
          echo "Usando ChromeDriver versão: $DRIVER_VERSION"

          wget https://storage.googleapis.com/chrome-for-testing-public/$DRIVER_VERSION/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver
          chromedriver --version

      - name: Instalar dependências Python
        run: |
          pip install selenium fake-useragent

      - name: Executar automação
        run: python3 scheduler.py

